name: Scheduled Maintenance

on:
  schedule:
    - cron: '0 2 * * *'  # Runs at 2 AM every day

jobs:
  maintenance:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run maintenance script
      run: ./scripts/maintenance.sh
